# Generated by Django 5.2.17 on 2026-09-07 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chores', '0009_alter_choreoccurrence_status'),
        ('households', '0004_household_is_paused_household_paused_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('chore_completed', 'Chore Completed'), ('chore_completed_late', 'Chore Completed Late'), ('chore_missed', 'Chore Missed'), ('chore_disputed', 'Chore Disputed'), ('chore_verified', 'Chore Verified'), ('chore_swap_accepted', 'Chore Swap Accepted'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('member_absence_approved', 'Member Absence Approved'), ('household_paused', 'Household Paused'), ('household_resumed', 'Household Resumed')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('chore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='chores.chore')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='households.household')),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='chores.choreoccurrence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
