# Generated by Django 5.2.17 on 2026-09-07 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_alter_choreoccurrence_status'),
        ('households', '0003_absencerequest_absencerequestvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Whether chore activity is frozen across the household without missed penalties.'),
        ),
        migrations.AddField(
            model_name='household',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the household chore activity was paused.', null=True),
        ),
        migrations.CreateModel(
            name='HouseholdAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('unassigned_occurrence', 'Unassigned Occurrence'), ('household_pause', 'Household Pause')], default='unassigned_occurrence', max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='chores.chore')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='households.household')),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='chores.choreoccurrence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
