# Generated by Django 5.2.17 on 2026-09-06 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0002_joinrequest_leaverequest_joinrequestvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('effort_level', models.CharField(choices=[('small', 'Small (1 pt)'), ('medium', 'Medium (2 pts)'), ('large', 'Large (3 pts)')], default='medium', max_length=20)),
                ('recurrence_type', models.CharField(choices=[('none', 'One-off (None)'), ('calendar', 'Calendar (e.g. Days of week)'), ('interval', 'Interval (e.g. Every N days)')], default='none', max_length=20)),
                ('recurrence_rule', models.JSONField(blank=True, default=dict, help_text="Serialized schedule rules (e.g., {'days': ['mon', 'thu']} or {'interval': 7, 'unit': 'days'}).")),
                ('deadline_mode', models.CharField(choices=[('none', 'No Deadline'), ('specific', 'Specific Point / Duration'), ('flexible_window', 'Flexible Window')], default='none', max_length=20)),
                ('deadline_window_hours', models.PositiveIntegerField(blank=True, help_text='Duration in hours defining the deadline or flexible action window.', null=True)),
                ('is_multi_assignee', models.BooleanField(default=False, help_text='Whether this chore requires multiple roommates to independently complete.')),
                ('required_assignees_count', models.PositiveIntegerField(default=1, help_text='Number of distinct roommates required if multi-assignee is enabled.')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='households.household')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
