# Generated by Django 5.2.17 on 2026-09-07 00:10

import chores.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
        ('households', '0002_joinrequest_leaverequest_joinrequestvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('effort_level', models.CharField(choices=[('small', 'Small (1 pt)'), ('medium', 'Medium (2 pts)'), ('large', 'Large (3 pts)')], default='medium', max_length=20)),
                ('recurrence_type', models.CharField(choices=[('none', 'One-off (None)'), ('calendar', 'Calendar (e.g. Days of week)'), ('interval', 'Interval (e.g. Every N days)')], default='none', max_length=20)),
                ('recurrence_rule', models.JSONField(blank=True, default=dict)),
                ('deadline_mode', models.CharField(choices=[('none', 'No Deadline'), ('specific', 'Specific Point / Duration'), ('flexible_window', 'Flexible Window')], default='none', max_length=20)),
                ('deadline_window_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('is_multi_assignee', models.BooleanField(default=False)),
                ('required_assignees_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=chores.models.default_suggestion_expiry)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_chore', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestion', to='chores.chore')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_suggestions', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='households.household')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoreSuggestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chores.choresuggestion')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('suggestion', 'voter')},
            },
        ),
    ]
