# Generated by Django 5.2.17 on 2026-09-07 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choresuggestion_choresuggestionvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed'), ('completed_late', 'Completed Late'), ('disputed', 'Disputed')], default='upcoming', max_length=20)),
                ('scheduled_start', models.DateTimeField(help_text='Point in time when the action window opens for this occurrence.')),
                ('due_date', models.DateTimeField(blank=True, help_text='Deadline timestamp for this occurrence.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='chores.chore')),
            ],
            options={
                'ordering': ['scheduled_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_assignments', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.choreoccurrence')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('occurrence', 'user')},
            },
        ),
    ]
