# Generated by Django 5.2.17 on 2026-09-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_choreoccurrence_choreassignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choreoccurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'upcoming')), fields=('chore',), name='unique_upcoming_occurrence_per_chore'),
        ),
    ]
