# Generated by Django 5.2.17 on 2026-09-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_choreoccurrence_unique_upcoming_occurrence_per_chore'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreassignment',
            name='missed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choreassignment',
            name='was_missed',
            field=models.BooleanField(default=False, help_text='Audit flag permanently preserving that this assignment was missed past its deadline.'),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='missed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when occurrence became past-due and missed.', null=True),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='was_missed',
            field=models.BooleanField(default=False, help_text='Audit flag permanently preserving that this chore was missed past its deadline.'),
        ),
    ]
