# Generated by Django 5.2.17 on 2026-09-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_choreassignment_missed_at_choreassignment_was_missed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreassignment',
            name='proof_image',
            field=models.FileField(blank=True, help_text='Uploaded photo evidence of chore completion.', null=True, upload_to='chore_proofs/%Y/%m/'),
        ),
    ]
