# Generated by Django 5.2.17 on 2026-09-07 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_choreassignment_proof_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choreoccurrence',
            name='dispute_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='disputed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputed_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='is_disputed',
            field=models.BooleanField(default=False, help_text='Whether this completion is flagged as disputed.'),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this chore completion was formally verified by a roommate.'),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_occurrences', to=settings.AUTH_USER_MODEL),
        ),
    ]
