# Generated by Django 5.2.17 on 2026-09-07 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_choreoccurrence_dispute_reason_and_more'),
        ('households', '0002_joinrequest_leaverequest_joinrequestvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choreassignment',
            name='is_swapped',
            field=models.BooleanField(default=False, help_text='Flag indicating this assignment was swapped as a personal favor.'),
        ),
        migrations.AddField(
            model_name='choreassignment',
            name='original_user',
            field=models.ForeignKey(blank=True, help_text='Original assignee before any personal favor chore swap.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_chore_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChoreSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='households.household')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_swaps', to=settings.AUTH_USER_MODEL)),
                ('proposer_occurrence', models.ForeignKey(help_text='Chore occurrence offered by the proposer.', on_delete=django.db.models.deletion.CASCADE, related_name='proposer_swaps', to='chores.choreoccurrence')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL)),
                ('recipient_occurrence', models.ForeignKey(blank=True, help_text='Chore occurrence requested from recipient in exchange (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_swaps', to='chores.choreoccurrence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
