# Generated by Django 5.2.17 on 2026-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_choreassignment_is_swapped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreoccurrence',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed'), ('completed_late', 'Completed Late'), ('disputed', 'Disputed'), ('unassigned', 'Unassigned')], default='upcoming', max_length=20),
        ),
    ]
